brand_list = ['Acura', 'Alfa', 'Audi', 'BMW', 'Bentley', 'Buick', 'Cadillac', 'Chevrolet', 'Chrysler',
                               'Dodge', 'Ford', 'GMC', 'Genesis', 'Honda', 'Hummer', 'Hyundai', 'INFINITI', 'Jaguar',
                               'Jeep', 'Kia', 'Lamborghini', 'Land', 'Lexus', 'Lincoln', 'MINI', 'Maserati', 'Mazda',
                               'Mercedes-Benz', 'Mitsubishi', 'Nissan', 'Porsche', 'RAM', 'Subaru', 'Toyota', 'Volkswagen', 'Volvo']


fuel_list = ['Diesel', 'E85 Flex Fuel', 'Gasoline', 'Hybrid', 'Plug-In Hybrid']

columns = {
    'model_year': 'int64',
    'milage': 'int64',
    'accident': 'int64',
    'HP': 'float64',
    'Engine Volume (L)': 'float64',
    'brand_Acura': 'bool',
    'brand_Alfa': 'bool',
    'brand_Audi': 'bool',
    'brand_BMW': 'bool',
    'brand_Bentley': 'bool',
    'brand_Buick': 'bool',
    'brand_Cadillac': 'bool',
    'brand_Chevrolet': 'bool',
    'brand_Chrysler': 'bool',
    'brand_Dodge': 'bool',
    'brand_Ford': 'bool',
    'brand_GMC': 'bool',
    'brand_Genesis': 'bool',
    'brand_Honda': 'bool',
    'brand_Hummer': 'bool',
    'brand_Hyundai': 'bool',
    'brand_INFINITI': 'bool',
    'brand_Jaguar': 'bool',
    'brand_Jeep': 'bool',
    'brand_Kia': 'bool',
    'brand_Lamborghini': 'bool',
    'brand_Land': 'bool',
    'brand_Lexus': 'bool',
    'brand_Lincoln': 'bool',
    'brand_MINI': 'bool',
    'brand_Maserati': 'bool',
    'brand_Mazda': 'bool',
    'brand_Mercedes-Benz': 'bool',
    'brand_Mitsubishi': 'bool',
    'brand_Nissan': 'bool',
    'brand_Porsche': 'bool',
    'brand_RAM': 'bool',
    'brand_Subaru': 'bool',
    'brand_Toyota': 'bool',
    'brand_Volkswagen': 'bool',
    'brand_Volvo': 'bool',
    'fuel_type_Diesel': 'bool',
    'fuel_type_E85 Flex Fuel': 'bool',
    'fuel_type_Gasoline': 'bool',
    'fuel_type_Hybrid': 'bool',
    'fuel_type_Plug-In Hybrid': 'bool',
    'transmission_False': 'bool',
    'transmission_True': 'bool'
}